eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FNB_database;encrypt=false;trustServerCertificate=true
    username: sa
    password: Nkabinde@442
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


server:
  port: 8201