eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5


spring:
  cloud:
    gateway:
      routes:
        - id: momentum-integration
          uri: http://localhost:8202
          predicates:
            - Path=/gateway/momentum/**
        - id: ebCore
          uri: http://localhost:8201
          predicates:
            - Path=/gateway/ebCore/**

server:
  servlet:
    context-path: /gateway
  port: 8200